name: Build
on: ["push", "pull_request"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
          registry-url: https://registry.npmjs.org/
      - name: Install modules
        run: npm install
      - name: Run eslint
        run: npm run test:lint
      - name: Run jest
        run: npm run test